// <auto-generated />
using System;
using Infraestructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infraestructure.Migrations
{
    [DbContext(typeof(SqlContext))]
    [Migration("20220124150847_InitialDB")]
    partial class InitialDB
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Domain.Entities.ContaCorrente", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("agencia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("contacorrente")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dt_abertura")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("dt_ultima_movimentacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("pessoa_fisica_id")
                        .HasColumnType("int");

                    b.Property<float>("saldo")
                        .HasColumnType("real");

                    b.Property<float>("saldo_abertura")
                        .HasColumnType("real");

                    b.Property<bool>("st_ativo")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("ContasCorrentes");
                });

            modelBuilder.Entity("Domain.Entities.Movimentacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<int>("conta_corrente_id")
                        .HasColumnType("int");

                    b.Property<string>("descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dt_movimentacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("operacao_id")
                        .HasColumnType("int");

                    b.Property<bool>("st_ativo")
                        .HasColumnType("bit");

                    b.Property<float>("valor")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Movimentacoes");
                });

            modelBuilder.Entity("Domain.Entities.Operacao", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("st_ativo")
                        .HasColumnType("bit");

                    b.Property<int>("tipo_id")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("Operacoes");
                });

            modelBuilder.Entity("Domain.Entities.PessoaFisica", b =>
                {
                    b.Property<int?>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("cpf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dt_nascimento")
                        .HasColumnType("datetime2");

                    b.Property<string>("nome")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("nu_sexo")
                        .HasColumnType("int");

                    b.Property<bool>("st_ativo")
                        .HasColumnType("bit");

                    b.HasKey("id");

                    b.ToTable("PessoasFisicas");
                });
#pragma warning restore 612, 618
        }
    }
}
